
export const appTexts: Record<string, any> = {
  ar: {
    appTitle: "تطبيق التفتيش",
    appDescription: "تطبيق تدبير أنشطة المفتش التربوي",
    // Inspector Modal
    inspectorModal_title: "بيانات المفتش",
    inspectorModal_fullName: "الإسم الكامل",
    inspectorModal_financialId: "رقم التأجير",
    inspectorModal_financialIdPlaceholder: "رقم التأجير...",
    inspectorModal_framework: "الإطار",
    inspectorModal_selectFramework: "اختر الإطار",
    inspectorModal_academy: "الأكاديمية الجهوية",
    inspectorModal_directorate: "المديرية الإقليمية",
    inspectorModal_subject: "التخصص",
    inspectorModal_subjectPlaceholder: "مثلا: التربية البدنية والرياضية",
    inspectorModal_securityTitle: "الأمان",
    inspectorModal_newPassword: "كلمة المرور الجديدة",
    inspectorModal_confirmPassword: "تأكيد كلمة المرور",
    inspectorModal_passwordPlaceholder: "اتركها فارغة إذا لم ترد التغيير",
    inspectorModal_passwordMismatch: "كلمات المرور غير متطابقة",
    framework_inspector_primary: "مفتش التعليم الإبتدائي",
    framework_inspector_middle: "مفتش التعليم الثانوي الإعدادي",
    framework_inspector_high: "مفتش التعليم الثانوي التأهيلي",
    select_academy: "اختر الأكاديمية",
    select_directorate: "اختر المديرية",
    save: "حفظ",
    cancel: "إلغاء",
    all: "الكل",
    confirmDelete: "تأكيد",
    clear: "مسح",
    
    // Home
    home_pageTitle: "الرئيسية",
    home_inspectorCardTitle: "المفتش",
    home_inspectorCardDesc: "تعديل البيانات الشخصية والإدارية",
    home_teachersCardTitle: "هيئة التدريس",
    home_teachersCardDesc: "تدبير ملفات الأساتذة والزيارات",
    home_inspectionSpaceCardTitle: "فضاء التفتيش",
    home_reportsCardTitle: "تقارير التفتيش ",
    home_reportsCardDesc: "الاطلاع على تقارير التفتيش والزيارات",
    home_otherReportsCardTitle: "تقارير أخرى",
    home_otherReportsCardDesc: "المراسلات والتقارير الإدارية",
    home_transmissionSlipCardTitle: "ورقة الارسال",
    home_transmissionSlipCardDesc: "وثيقة ضبط المراسلات الإدارية ",
    home_activitySummaryCardTitle: "البرنامج والحصيلة",
    home_activitySummaryCardDesc: "الحصيلة الدورية والسنوية للأنشطة والبرنامج",
    home_settingsCardTitle: "الإعدادات",
    home_statisticsCardTitle: "الإحصائيات",
    home_statisticsCardDesc: "مؤشرات ورسوم بيانية حول الأداء",
    home_researchCardTitle: "البحث التربوي",
    home_researchCardDesc: "موجه منهجي لإعداد البحوث التربوية",
    
    // Teachers List
    teachersList_pageTitle: "لائحة الأساتذة",
    teachersList_selectTitle: "اختيار أستاذ",
    teachersList_addTeacher: "إضافة أستاذ",
    teachersList_searchLabel: "بحث",
    teachersList_searchPlaceholder: "بحث بالإسم أو المؤسسة...",
    teachersList_selectAlertTitle: "تنبيه",
    teachersList_selectAlertText: "المرجو اختيار أستاذ من اللائحة",
    teachersList_addTeachersFirst: "المرجو إضافة أساتذة أولاً",
    teachersList_colFullName: "الإسم الكامل",
    teachersList_colInstitution: "المؤسسة",
    teachersList_colFramework: "الإطار",
    teachersList_colLastScore: "آخر نقطة",
    teachersList_colActions: "إجراءات",
    teachersList_noResults: "لا توجد نتائج",
    select: "اختيار",
    viewDetails: "التفاصيل",
    edit: "تعديل",
    delete: "حذف",
    importFromExcel: "استيراد من Excel",
    importHelp_title: "تعليمات الاستيراد",
    importHelp_intro: "يجب أن يحتوي ملف Excel على الأعمدة التالية:",
    importHelp_col1: "<b>fullName</b>: الإسم الكامل",
    importHelp_col2: "<b>employeeId</b>: رقم التأجير",
    importHelp_col3: "<b>genre</b>: الجنس (ذكر/أنثى)",
    importHelp_col4: "<b>framework</b>: الإطار",
    importHelp_col5: "<b>institution</b>: المؤسسة",
    importHelp_col6: "<b>subject</b>: المادة",
    importHelp_col7: "<b>grade</b>: الدرجة",
    importHelp_col8: "<b>rank</b>: الرتبة",
    importHelp_col9: "<b>lastInspectionScore</b>: آخر نقطة تفتيش",
    importHelp_col10: "<b>lastInspectionDate</b>: تاريخ آخر تفتيش (YYYY-MM-DD)",
    importHelp_col11: "<b>lastInspector</b>: إسم المفتش السابق",
    importHelp_col12: "<b>image</b>: رابط الصورة (اختياري)",
    importHelp_col13: "<b>promotionPace</b>: نسق الترقية (rapid/medium/slow)",
    importHelp_button_proceed: "متابعة للاستيراد",
    errorImportInvalidFormat: "صيغة الملف غير صحيحة",
    errorImport: "حدث خطأ أثناء الاستيراد",
    
    // Teacher Detail
    teacherDetail_pageTitle: "ملف الأستاذ",
    teacherDetail_addVisit: "إضافة زيارة",
    teacherDetail_addInspection: "إضافة تفتيش",
    teacherDetail_infoCardTitle: "المعلومات المهنية",
    teacherDetail_historyCardTitle: "سجل الزيارات والتفتيشات",
    teacherDetail_noReports: "لا توجد تقارير مسجلة",
    teacher_female: "الأستاذة",
    teacher_male: "الأستاذ",
    teacher_fullName: "الإسم الكامل",
    teacher_subject: "المادة",
    teacher_lastScore: "آخر نقطة",
    teacher_employeeId: "رقم التأجير",
    teacher_grade: "الدرجة",
    teacher_lastDate: "تاريخ آخر تفتيش",
    teacher_framework: "الإطار",
    teacher_rank: "الرتبة",
    teacher_lastInspector: "المفتش",
    teacher_institution: "المؤسسة",
    teacher_genre: "الجنس",
    teacher_recruitmentDate: "تاريخ التوظيف",
    teacher_tenureDate: "تاريخ الترسيم",
    teacher_gradeDate: "تاريخ الدرجة",
    teacher_rankDate: "تاريخ الرتبة",
    genre_male: "ذكر",
    genre_female: "أنثى",
    back: "رجوع",
    home: "الرئيسية",
    visit: "زيارة",
    inspection: "تفتيش",
    reportDatePrefix: "التاريخ",
    reportHasLessonPlan: "مرفق بصورة الجذاذة",
    viewExport: "معاينة / تصدير",
    sector_label: "القطاع",
    sector_public: "عمومي",
    sector_private: "خصوصي",
    
    // Add Teacher Modal
    addTeacherModal_addTitle: "إضافة أستاذ جديد",
    addTeacherModal_editTitle: "تعديل بيانات الأستاذ",
    addTeacherModal_saveTeacher: "إضافة الأستاذ",
    addTeacherModal_saveChanges: "حفظ التغييرات",
    addTeacherModal_fillAllFields: "المرجو ملء جميع الحقول الضرورية",
    addTeacherModal_selectFramework: "اختر الإطار",
    addTeacherModal_selectSubject: "اختر المادة",
    addTeacherModal_selectGrade: "اختر الدرجة",
    addTeacherModal_lastInspectionTitle: "بيانات التفتيش السابق",
    framework_primary: "أستاذ التعليم الإبتدائي",
    framework_middle: "أستاذ التعليم الثانوي الإعدادي",
    framework_high: "أستاذ التعليم الثانوي التأهيلي",
    
    // Report Modal / Evaluation
    reportModal_lessonObservation: "ملاحظات حول سير الدرس",
    evaluation_field_tools: "الوسائل التعليمية",
    evaluation_field_studentCount: "عدد التلاميذ",
    evaluation_field_class: "القسم",
    evaluation_field_level: "المستوى",
    evaluation_field_activity: "النشاط",
    evaluation_field_activityCategory: "نوع النشاط",
    evaluation_field_lessonGoal: "هدف الحصة",
    evaluation_criterion: "معيار",
    reportModal_criteria: "المعايير والمؤشرات",
    report_dateLabel: "حرر بتاريخ",
    report_awardedScore: "النقطة الممنوحة",
    signature_title_1: "توقيع المفتش",
    signature_regionalDirector: "توقيع المدير الإقليمي",
    signature_institutionDirector: "توقيع مدير المؤسسة",
    errorPopupBlocker: "تم حظر النافذة المنبثقة. المرجو السماح بالنوافذ المنبثقة للطباعة.",
    errorExportLibrary: "مكتبات التصدير غير متوفرة",
    close: "إغلاق",
    share: "مشاركة",
    exportWord: "Word تصدير",
    exportPdf: "PDF تصدير",
    print: "طباعة",
    inspectionReport: "تقرير تفتيش",
    visitReport: "تقرير زيارة صفية",
    ministryLogoAlt: "شعار الوزارة",
    regionalAcademyLabel: "الأكاديمية الجهوية:",
    regionalDirectorateLabel: "المديرية الإقليمية:",
    department_pedagogicalAffairs: "مصلحة الشؤون التربوية والخريطة المدرسية",
    
    // Reports List
    reportsList_pageTitle: "أرشيف التقارير",
    reportsList_newReport: "تقرير جديد",
    reportsList_filterTitle: "تصفية",
    teacher: "الأستاذ",
    reportsList_allTeachers: "جميع الأساتذة",
    reportsList_reportType: "نوع التقرير",
    reportsList_allTypes: "الكل",
    reportsList_academicYear: "الموسم الدراسي",
    reportsList_allYears: "جميع المواسم",
    type: "النوع",
    date: "التاريخ",
    score: "النقطة",
    actions: "إجراءات",
    reportsList_noResults: "لا توجد تقارير",
    
    // Evaluation Page
    evaluation_scoreLabel: "النقطة المقترحة (على 20)",
    evaluation_scoreRequired: "المرجو إدخال النقطة",
    evaluation_generatingAI: "جاري توليد الملاحظات بالذكاء الاصطناعي...",
    evaluation_generateAIBtn: "توليد الملاحظات (AI)",
    evaluation_generateAIForCriterion: "تحرير بالذكاء الاصطناعي",
    evaluation_mustHaveOneCriterion: "يجب أن يبقى معيار واحد على الأقل",
    evaluation_fieldValuePlaceholder: "أدخل المحتوى...",
    reportModal_lessonPlanSectionTitle: "صورة الجذاذة (اختياري)",
    evaluation_changeLessonPlanImage: "تغيير الصورة",
    evaluation_removeLessonPlanImage: "حذف الصورة",
    evaluation_takePhoto: "التقاط صورة",
    evaluation_uploadImage: "تحميل صورة",
    evaluation_criterionNamePlaceholder: "إسم المعيار",
    evaluation_commentsPlaceholder: "ملاحظات حول {0}...",
    evaluation_addCriterion: "إضافة معيار",
    otherReportModal_title: "معاينة التقرير",
    settings_selectCategory: "اختر الصنف",
    settings_selectActivity: "اختر النشاط",
    evaluation_selectLevel: "اختر المستوى",
    exportExcel: "Excel تصدير",
    exportHtml: "HTML تصدير",
    reportModal_newScore: "النقطة الممنوحة",
    report: "تقرير",
    unnamedField: "غير معنون",
    reportTemplate_standard: 'التقرير الوصفي',
    reportTemplate_network: 'تقرير شبكة المفتشية',
    overallAssessment: 'التقدير الإجمالي',
    overallAssessmentPlaceholder: 'أدخل التقدير الإجمالي هنا...',
    achievementLevel_placeholder: 'مستوى الإنجاز',
    achievementLevel_1: 'غير متحكم فيه',
    achievementLevel_2: 'في طور التحكم',
    achievementLevel_3: 'متحكم فيه',
    achievementLevel_4: 'متحكم فيه بامتياز',
    
    // Other Reports
    otherReports_pageTitle: "تقارير ومراسلات أخرى",
    otherReports_formTitle: "إعداد تقرير أو مراسلة",
    editReport: "تعديل التقرير",
    otherReports_documentNumber: "رقم الإرسال:",
    otherReports_department: "إلى السيد(ة)",
    otherReports_selectDepartment: "اختر الجهة المرسل إليها",
    otherReports_subject: "الموضوع",
    otherReports_subjectPlaceholder: "موضوع التقرير أو المراسلة...",
    otherReports_reference: "المرجع",
    otherReports_referencePlaceholder: "مرجع المراسلة (اختياري)...",
    otherReports_addReference: "إضافة مرجع",
    otherReports_content: "المحتوى",
    otherReports_invitedTeachersTitle: "الأساتذة المعنيون / المدعوون",
    otherReports_searchTeacher: "بحث عن أستاذ...",
    otherReports_selectAll: "تحديد الكل",
    saveChanges: "حفظ التغييرات",
    otherReports_rephraseError: "خطأ في الصياغة",
    view: "معاينة",
    report_reference_field: "المرجع:",
    report_from: "من السيد:",
    report_framework_label: "الإطار:",
    report_subject_label: "التخصص:",
    report_to: "إلى:",
    report_subject_field: "الموضوع:",
    report_signature_line: "والسلام",
    otherReports_invitedListTitle: "لائحة الأساتذة",
    
    // Transmission Slip
    transmissionSlip_pageTitle: "جدول الإرسال",
    transmissionSlip_createTitle: "إعداد جدول إرسال جديد",
    transmissionSlip_editTitle: "تعديل جدول الإرسال",
    slip_slipNumber: "رقم الإرسال",
    transmissionSlip_slipNumberPlaceholder: "مثلاً: 12/2023",
    transmissionSlip_attachedReports: "الوثائق المرفقة",
    transmissionSlip_noReportsAdded: "لم يتم إضافة أي وثائق بعد",
    slip_item_copies: "عدد النسخ",
    slip_item_notes: "ملاحظات",
    transmissionSlip_addActivities: "إضافة تقارير من الأرشيف",
    transmissionSlip_savedSlips: "جداول الإرسال المحفوظة",
    transmissionSlip_noSavedSlips: "لا توجد جداول إرسال محفوظة",
    transmissionSlip_fillAllFields: "المرجو ملء جميع الحقول واختيار وثيقة واحدة على الأقل",
    cancelEdit: "إلغاء التعديل",
    selectActivities_title: "اختيار وثائق للإرسال",
    selectActivities_add: "إضافة ({0})",
    selectActivities_noReports: "لا توجد تقارير غير مرسلة",
    subject: "الموضوع",
    transmissionSlipModal_title: "معاينة جدول الإرسال",
    slip_item_seq: "ر.ت",
    slip_item_subject: "نوع الوثيقة وموضوعها",
    slip_activity_summary: "حصيلة الأنشطة",
    
    // Activity Summary
    activitySummary_pageTitle: "الحصيلة السنوية",
    activitySummary_reportType: "نوع النشاط",
    activitySummary_allTypes: "جميع الأنشطة",
    activitySummary_searchPlaceholder: "بحث في الموضوع...",
    activitySummary_noReports: "لا توجد أنشطة مسجلة في هذه الفترة.",
    activitySummary_type_visit: "زيارات",
    activitySummary_type_inspection: "تفتيشات",
    activitySummary_type_other: "أنشطة أخرى",
    activitySummary_type_experimentalLessons: "الدروس التجريبية",
    activitySummary_type_seminars: "الندوات واللقاءات التربوية",
    activitySummary_type_trainings: "التكوينات",
    activitySummary_type_sharedWork: "العمل المشترك",
    activitySummary_type_tenure: "الترسيم والكفاءة",
    
    // Activity Summary Periods
    activitySummary_choosePeriod: "اختيار فترة الحصيلة",
    activitySummary_semester: "الأسدس",
    activitySummary_semester1: "الأسدس الأول",
    activitySummary_semester2: "الأسدس الثاني",
    activitySummary_annual: "البرنامج والحصيلة",
    activitySummary_archiveTitle: "أرشيف المواسم الدراسية",
    activitySummary_startDate: "تاريخ البداية",
    activitySummary_endDate: "تاريخ النهاية",
    activitySummary_showReports: "عرض الحصيلة",
    activitySummary_changePeriod: "تغيير الفترة / الدورة",
    activitySummary_periodDateLabel: "عن الفترة الممتدة من {0} إلى {1}",
    
    // Inspection Space
    inspectionSpace_pedagogicalReports: "تقارير تربوية",
    inspectionSpace_title: "هيئة التدريس",
    inspectionSpace_button: "هيئة التدريس",
    inspectionSpace_exit: "خروج",
    inspectionSpace_chooseDay: "اختر اليوم",
    inspectionSpace_startTime: "ساعة البداية",
    inspectionSpace_duration: "المدة الزمنية",
    inspectionSpace_morning: "صباح",
    inspectionSpace_afternoon: "مساء",
    inspectionSpace_hour: "ساعة",
    inspectionSpace_hours: "ساعات",
    inspectionSpace_status_busy: "في حصة",
    inspectionSpace_status_free: "فارغ",
    inspectionSpace_status_onLeave: "رخصة",
    inspectionSpace_available: "متاح",
    inspectionSpace_busy: "مشغول",
    
    // Teacher Schedule Modal
    scheduleModal_title: "بطاقة معلومات الأستاذ",
    scheduleModal_tab_card: "بطاقة المعلومات",
    scheduleModal_tab_timetable: "جدول الحصص",

    // Statistics
    statistics_pageTitle: "لوحة الإحصائيات",
    statistics_visits: "الزيارات",
    statistics_inspections: "التفتيشات",
    statistics_other: "تقارير أخرى",
    statistics_total: "المجموع العام",
    statistics_chartTitle: "تطور الأنشطة حسب الأشهر",
    statistics_distributionTitle: "توزيع الأنشطة",
    
    // Educational Research
    research_pageTitle: "البحث التربوي",
    research_placeholderTopic: "أدخل موضوع البحث التربوي...",
    research_generateButton: "توليد المقترح المنهجي",
    research_generating: "جاري إعداد الموجه...",
    research_section_problem: "الإشكالية المقترحة",
    research_section_hypothesis: "الفرضيات",
    research_section_methodology: "المنهجية والأدوات",
    research_section_plan: "تصميم البحث المقترح",
    research_helpText: "هذه النافذة تساعدك في بناء هيكلة أولية للبحث التربوي.",
    research_btn_instruments: "توليد نماذج الأدوات والمعايير",
    research_section_instruments: "تفاصيل أدوات البحث وشبكات التفريغ",

    // Settings
    settings_pageTitle: "الإعدادات",
    settings_tab_general: "عامة",
    settings_tab_reports: "التقارير",
    settings_fontSize: "حجم الخط",
    fontSize_reset: "إعادة تعيين",
    settings_ministryTitle: "ترويسة التقارير",
    settings_ministryDesc: "تخصيص الشعار والبيانات الإدارية",
    settings_ministryLogoLabel: "شعار الوزارة",
    settings_changeLogo: "تغيير الشعار",
    settings_logoSpecs: "يفضل استخدام صورة PNG بخلفية شفافة",
    settings_logoHeight: "ارتفاع الشعار",
    settings_aiConfig: "إعدادات الذكاء الاصطناعي",
    settings_geminiApiKey: "مفتاح API الخاص بـ Gemini",
    settings_geminiApiKeyHelp: "مطلوب لاستخدام ميزات الذكاء الاصطناعي في صياغة التقارير. يمكنك الحصول عليه مجاناً من Google AI Studio.",
    settings_getApiKey: "احصل على المفتاح من هنا",
    settings_academiesTitle: "الأكاديميات",
    settings_academiesDesc: "قائمة الأكاديميات الجهوية",
    settings_academyPlaceholder: "اسم الأكاديمية...",
    settings_addAcademy: "إضافة أكاديمية",
    settings_directoratesTitle: "المديريات",
    settings_directoratesDesc: "قائمة المديريات الإقليمية",
    settings_directoratePlaceholder: "اسم المديرية...",
    settings_addDirectorate: "إضافة مديرية",
    settings_departmentsTitle: "الأقسام والمصالح",
    settings_departmentsDesc: "الجهات المرسل إليها (رؤساء المصالح...)",
    settings_departmentPlaceholder: "اسم المصلحة...",
    settings_addDepartment: "إضافة مصلحة",
    settings_backupRestoreTitle: "النسخ الاحتياطي والاستعادة",
    settings_backupRestoreDesc: "حفظ البيانات محلياً أو استعادتها",
    settings_backupButton: "تحميل نسخة احتياطية",
    settings_restoreButton: "استعادة نسخة",
    settings_levelsTitle: "المستويات الدراسية",
    settings_levelsDesc: "المستويات المتاحة في التقارير",
    settings_levelPlaceholder: "اسم المستوى...",
    settings_addLevel: "إضافة مستوى",
    settings_subjectsListTitle: "المواد والتخصصات",
    settings_subjectsManagementDesc: "قائمة المواد الدراسية",
    settings_subjectPlaceholder: "اسم المادة...",
    settings_addSubject: "إضافة مادة",
    settings_activitiesTitle: "الأنشطة الرياضية",
    settings_activitiesDesc: "تخصيص قائمة الأنشطة حسب النوع",
    settings_newCategoryPrompt: "صنف جديد...",
    settings_newActivityPrompt: "نشاط جديد...",
    settings_selectCategoryPrompt: "اختر صنفاً لعرض أنشطته",
    settings_criteriaTitle: "معايير التقييم الافتراضية",
    settings_criteriaDesc: "المعايير التي تظهر في التقارير الجديدة",
    settings_criterionPlaceholder: "نص المعيار...",
    settings_addCriterion: "إضافة معيار",
    settings_confirmDeleteCategory: "هل أنت متأكد من حذف الصنف '{0}' وجميع أنشطته؟",
    settings_logoSizeError: "حجم الملف كبير جداً (أقصى حد 500 كيلوبايت)",
    errorBackup: "حدث خطأ أثناء النسخ الاحتياطي",
    errorReadFile: "حدث خطأ أثناء قراءة الملف",
    successRestore: "تمت استعادة البيانات بنجاح",
    errorRestore: "خطأ في استعادة البيانات (ملف غير صالح)",
    confirmRestoreTitle: "تأكيد الاستعادة",
    confirmRestoreMessage: "ستؤدي استعادة البيانات إلى استبدال جميع البيانات الحالية. هل أنت متأكد؟",
    confirmRestoreButton: "نعم، استعد البيانات",
    
    // Login
    login_title: "تسجيل الدخول",
    login_subTitle: "فضاء المفتش التربوي",
    login_nameLabel: "الإسم الكامل",
    login_placeholderName: "أدخل إسمك الكامل",
    login_passwordLabel: "كلمة المرور",
    login_placeholderPassword: "أدخل كلمة المرور",
    login_rememberMe: "تذكرني",
    login_button: "دخول",
    login_errorPassword: "كلمة المرور غير صحيحة",
    themeSwitcher_toDark: "الوضع المظلم",
    themeSwitcher_toLight: "الوضع المضيء",
    about_tooltip: "حول التطبيق",
    
    // Messages
    successInspectorSave: "تم حفظ بيانات المفتش بنجاح",
    errorOccurredWithMessage: "حدث خطأ: {0}",
    successSettingsSave: "تم حفظ الإعدادات بنجاح",
    successTeacherUpdate: "تم تحديث بيانات الأستاذ بنجاح",
    successTeacherAdd: "تمت إضافة الأستاذ بنجاح",
    successTeacherDelete: "تم حذف الأستاذ بنجاح",
    confirmDeleteTitle_teacher: "حذف أستاذ",
    confirmDeleteMessage_teacher: "هل أنت متأكد من حذف هذا الأستاذ؟ سيتم حذف جميع التقارير المرتبطة به.",
    successTeachersImport: "تم استيراد الأساتذة بنجاح",
    confirmImportTitle: "تأكيد الاستيراد",
    confirmImportMessage: "سيتم استبدال القائمة الحالية بالكامل. هل تريد المتابعة؟",
    confirmImportButton: "نعم، استبدل القائمة",
    successReportSave: "تم حفظ التقرير بنجاح",
    errorReportSave: "خطأ في حفظ التقرير",
    successReportDelete: "تم حذف التقرير بنجاح",
    confirmDeleteTitle_report: "حذف التقرير",
    confirmDeleteTitle_academicYear: "حذف الموسم الدراسي",
    confirmDeleteMessage_report: "هل أنت متأكد من حذف هذا التقرير؟ لا يمكن التراجع عن هذه العملية.",
    confirmDeleteMessage_academicYear: "هل تريد فعلا حذف تقارير هذا الموسم الدراسي؟",
    successSlipSave: "تم حفظ جدول الإرسال بنجاح",
    successSlipDelete: "تم حذف جدول الإرسال بنجاح",
    confirmDeleteTitle_slip: "حذف جدول الإرسال",
    confirmDeleteMessage_slip: "هل أنت متأكد من حذف جدول الإرسال هذا؟",
    errorOfflineSync: "لا يوجد اتصال بالإنترنت. تعذر المزامنة.",
    errorApiKeyMissingBuild: "مفتاح API الخاص بالذكاء الاصطناعي غير متوفر. يرجى إعداده في إعدادات البيئة.",
    errorOfflineAI: "لا يوجد اتصال بالإنترنت. الذكاء الاصطناعي يتطلب اتصالا نشطا.",
    onlineMode: "أنت متصل بالإنترنت",
    offlineMode: "أنت غير متصل بالإنترنت",
    logout_success: "تم تسجيل الخروج بنجاح",
    logout: "تسجيل الخروج",
    reportTypeModal_title: "نوع التقرير",
    reportTypeModal_description: "اختر نوع المهمة التي تود القيام بها:",
    
    // Professional Card in Inspection Space
    professionalCard_adminInfo: "المعلومات الإدارية",
    professionalCard_inspectionInfo: "آخر تفتيش",
    
    // Add Teacher Choice
    addTeacher_choiceTitle: "إضافة أستاذ",
    addTeacher_manual: "إضافة يدوية",
    addTeacher_excel: "استيراد ملف Excel",
    
    // About
    aboutModal_title: "حول التطبيق",
    aboutModal_philosophyTitle: "فلسفة التطبيق",
    aboutModal_philosophy_p1: "يعتبر تطبيق 'المفتش' منصة رقمية متكاملة صممت خصيصاً لتلبية الاحتياجات المهنية الدقيقة لمفتشي التربية البدنية والرياضية. ينبثق هذا المشروع من ضرورة عصرنة الممارسة المهنية وتجاوز الأساليب التقليدية في التدبير الإداري والتربوي، مما يتيح للمفتش التركيز أكثر على الجوانب التأطيرية والبيداغوجية.",
    aboutModal_philosophy_p2: "يهدف التطبيق إلى رقمنة شاملة لمسار التفتيش، بدءاً من الأرشفة الذكية لملفات الأساتذة، مروراً بالتحرير الآلي والمدعوم بالذكاء الاصطناعي للتقارير، وصولاً إلى الضبط الدقيق للمراسلات وتوليد الحصيلة السنوية بضغطة زر واحدة، مع ضمان أمن وخصوصية البيانات عبر التخزين المحلي والسحابي المشفر.",
    aboutModal_featuresTitle: "المميزات والوظائف الرئيسية",
    aboutModal_feature1_title: "التدبير الذكي لهيئة التدريس",
    aboutModal_feature1_desc: "قاعدة بيانات مركزية تتيح تتبع المسار المهني لكل أستاذ (الدرجة، الرتبة، تاريخ التوظيف...) مع إمكانية استيراد اللوائح من ملفات Excel وتصنيف الأساتذة حسب المؤسسات والقطاعات (عمومي/خصوصي).",
    aboutModal_feature2_title: "نظام تحرير التقارير المتقدم",
    aboutModal_feature2_desc: "واجهة مرنة لتحرير تقارير التفتيش والزيارات الصفية، مدعومة بمحرك ذكاء اصطناعي لصياغة الملاحظات التربوية بشكل احترافي. يدعم النظام تصدير الوثائق بصيغ Word و PDF جاهزة للطباعة مع الترويسة الرسمية.",
    aboutModal_feature3_title: "فضاء التفتيش والقيادة",
    aboutModal_feature3_desc: "لوحة قيادة تفاعلية توفر رؤية شاملة للخريطة التربوية، حيث يمكن تتبع جداول حصص الأساتذة، وضعياتهم الإدارية، وتحديد المتاحين منهم للزيارة أو التفتيش في الوقت الفعلي.",
    aboutModal_feature4_title: "تدبير المراسلات وجداول الإرسال",
    aboutModal_feature4_desc: "مكتبة من النماذج الجاهزة للمراسلات الإدارية، تقارير الندوات، واللقاءات التربوية. كما يتضمن نظاماً لإنشاء جداول الإرسال (Bordereaux d'envoi) لضبط وتتبع حركة الوثائق الصادرة.",
    aboutModal_feature5_title: "الحصيلة الدورية والإحصائيات",
    aboutModal_feature5_desc: "توليد تلقائي وشامل لحصيلة الأنشطة (الأسدس الأول، الثاني، السنوية) مع رسوم بيانية توضح تطور الأداء. يتضمن النظام أرشيفاً منظماً حسب المواسم الدراسية لسهولة العودة للبيانات السابقة.",
    aboutModal_howToUseTitle: "دليل الاستخدام السريع",
    aboutModal_step1_title: "1. إعداد الملف الشخصي والبيانات الأساسية:",
    aboutModal_step1_desc: "ابدأ بضبط بياناتك المهنية في صفحة 'المفتش'، ثم قم ببناء قاعدة بيانات الأساتذة إما يدوياً أو عبر خاصية الاستيراد السريع من ملف Excel لربح الوقت.",
    aboutModal_step2_title: "2. تنفيذ المهام الميدانية والتربوية:",
    aboutModal_step2_desc: "استخدم الأزرار السريعة في الواجهة الرئيسية لتوثيق الزيارات أو التفتيشات. يمكنك استغلال الذكاء الاصطناعي لتحسين صياغة الملاحظات وضمان جودة التقرير.",
    aboutModal_step3_title: "3. الحفظ، الأرشفة والتصدير الرقمي:",
    aboutModal_step3_desc_A: "يتم حفظ جميع تحركاتك تلقائياً في ذاكرة الجهاز لضمان العمل دون إنترنت.",
    aboutModal_step3_desc_B: "يمكنك في أي وقت معاينة الوثائق وتصديرها بصيغ احترافية (Word/PDF) أو مشاركتها مباشرة عبر الوسائط الرقمية.",
    aboutModal_step4_title: "4. الأمان والنسخ الاحتياطي المنتظم:",
    aboutModal_step4_desc: "احرص على إجراء نسخ احتياطي لبياناتك دورياً من الإعدادات. كما يمكنك تفعيل المزامنة السحابية لضمان الوصول لبياناتك من أي جهاز آخر بأمان تام.",
    aboutModal_closing: "تم تطوير هذا التطبيق كمساهمة تقنية لتجويد منظومة التفتيش التربوي",
    
    // Image Viewer
    zoomIn: "تكبير",
    zoomOut: "تصغير",
    resetZoom: "إعادة تعيين",
    rotate: "تدوير",
    reset: "إعادة تعيين",
    
    // Days
    day_monday: "الإثنين",
    day_tuesday: "الثلاثاء",
    day_wednesday: "الأربعاء",
    day_thursday: "الخميس",
    day_friday: "الجمعة",
    day_saturday: "السبت",
    day_sunday: "الأحد",
    footerText: "جميع الحقوق محفوظة &copy; 2025 - تطبيق المفتش التربوي",
  }
};
